CREATE USER webapp WITH PASSWORD 'hf274q9e3';
ALTER USER webapp CREATEDB;
CREATE DATABASE webapp;
GRANT ALL PRIVILEGES ON DATABASE webapp to webapp;
\c webapp
GRANT CREATE ON SCHEMA PUBLIC TO webapp;
